#!/bin/sh
### BEGIN INIT INFO
# Provides:          app-monitor
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Application monitoring service
### END INIT INFO

NAME=app-monitor
DAEMON=/usr/local/sbin/app-monitor
CONFIG=/etc/app-monitor/config.json
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

case "$1" in
  start)
    echo "Starting $NAME..."
    start-stop-daemon --start --background --no-close \
      --make-pidfile --pidfile $PIDFILE \
      --exec $DAEMON -- $CONFIG >> $LOGFILE 2>&1
    ;;
  stop)
    echo "Stopping $NAME..."
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ] && kill -0 "$(cat $PIDFILE)" 2>/dev/null; then
      echo "$NAME is running (PID $(cat $PIDFILE))"
    else
      echo "$NAME is not running"
      exit 1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
